table DailyData
	lineageTag: c3697780-8827-4f94-b7a3-6c092c5d39b0

	column Occupied_Units
		dataType: int64
		formatString: 0
		lineageTag: 3bec40b9-ddcc-4a6f-8b26-30b4b6349ce9
		summarizeBy: sum
		sourceColumn: Occupied_Units

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: string
		lineageTag: 4df661ce-e95c-4ced-bc63-23e445a8e252
		summarizeBy: none
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column Occupancy
		dataType: double
		formatString: #,0.000
		lineageTag: 6d763b68-56bd-4f3b-a661-e31c3fcf25f0
		summarizeBy: sum
		sourceColumn: Occupancy

		annotation SummarizationSetBy = Automatic

	column Bookings
		dataType: int64
		formatString: 0
		lineageTag: 8010367a-baa2-4d87-a4df-4c65077dc51c
		summarizeBy: sum
		sourceColumn: Bookings

		annotation SummarizationSetBy = Automatic

	column Notices
		dataType: int64
		formatString: 0
		lineageTag: 772721e2-7569-428d-869e-863ef6bd5c55
		summarizeBy: sum
		sourceColumn: Notices

		annotation SummarizationSetBy = Automatic

	column Avg_Booking_Time
		dataType: double
		formatString: #,0.000
		lineageTag: 1eacc809-f3ff-4ddd-b1b8-7f43d4d65f1b
		summarizeBy: sum
		sourceColumn: Avg_Booking_Time

		annotation SummarizationSetBy = Automatic

	column Avg_Notice_Time
		dataType: double
		formatString: #,0.000
		lineageTag: a12e5933-3124-4787-973f-96c9f251c3b4
		summarizeBy: sum
		sourceColumn: Avg_Notice_Time

		annotation SummarizationSetBy = Automatic

	column Has_Bookings
		dataType: int64
		formatString: 0
		lineageTag: 5ad23083-fbdc-41e5-a032-ef5321c1049a
		summarizeBy: sum
		sourceColumn: Has_Bookings

		annotation SummarizationSetBy = Automatic

	column Has_Notices
		dataType: int64
		formatString: 0
		lineageTag: 1c7f545e-c193-42af-9514-2dfc50cedd83
		summarizeBy: sum
		sourceColumn: Has_Notices

		annotation SummarizationSetBy = Automatic

	column units_available
		dataType: double
		lineageTag: b9e582c4-dce3-4957-88bd-cf6068210e62
		summarizeBy: sum
		sourceColumn: units_available

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Missing_Occupancy_Flag
		dataType: int64
		formatString: 0
		lineageTag: 2e7d6d69-d7f3-48a4-a517-57fdbfe21cbb
		summarizeBy: sum
		sourceColumn: Missing_Occupancy_Flag

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: acdae6e7-7de2-4fa7-a501-cf616b268105
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition DailyData = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\FiercePC\Desktop\CH_Data\for dashboard\daily_cleaned_dataset.csv"),[Delimiter=",", Columns=12, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Occupied_Units", Int64.Type}, {"Week", type text}, {"Occupancy", type number}, {"Bookings", Int64.Type}, {"Notices", Int64.Type}, {"Avg_Booking_Time", type number}, {"Avg_Notice_Time", type number}, {"Has_Bookings", Int64.Type}, {"Has_Notices", Int64.Type}, {"units_available", type number}, {"Missing_Occupancy_Flag", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

