table Measure
	lineageTag: 853c3e16-b8ec-4fe9-ba83-75b0f0a53bdd

	measure 'Avg Booking Time' = AVERAGE(DailyData[Avg_Booking_Time])
		lineageTag: 62e26567-1b80-4ba6-901c-805532e0ea54

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Notice Time' = AVERAGE(DailyData[Avg_Notice_Time])
		lineageTag: ea615dce-7359-4b76-90e4-a6f720fb05c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Flow' = [Total Bookings] - [Total Notices]
		lineageTag: e948113c-4a64-4e28-a1e1-9e01bae3d8b4

	measure 'Total Bookings' = SUM(DailyData[Bookings])
		formatString: 0
		lineageTag: 169c0137-2db6-4789-9f4b-cfd4dcdd3197

	measure 'Total Notices' = SUM(DailyData[Notices])
		formatString: 0
		lineageTag: e5581e1b-62ae-4012-ab3b-80b5d4a5a651

	measure 'Occupancy %' =
			
			DIVIDE(
			    [Total Occupied Units],
			    [Total Units Available],
			    0
			)
		lineageTag: a61c4744-eb44-407e-a6a1-9e307c135eea

	measure 'Total Occupied Units' = SUM(DailyData[Occupied_Units])
		formatString: 0
		lineageTag: 2b4f5560-1fbb-4653-b739-4c9fc35a8b8c

	measure 'Total Units Available' = SUM(DailyData[units_available])
		lineageTag: 2a0b4030-1f51-49b1-8e3a-77991b28257f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Occupied Units' = AVERAGE(DailyData[Occupied_Units])
		lineageTag: 1640f54a-8f0d-4a1d-a8ff-8acc08114658

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Units Available' = AVERAGE(DailyData[units_available])
		lineageTag: d2ceff3d-cf48-4263-b882-80ed8c74ca5e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Net Flow' =
			
			AVERAGEX(
			    VALUES('DateTable'[Date]),
			    [Net Flow]
			)
		lineageTag: ca7a7961-8542-456a-aebf-a72d879ab85d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column
		formatString: 0
		lineageTag: 4d97ec73-b8db-442e-a656-5015c7a3b23d
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition Measure = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = c2460433b71c4411b38595b26863511a

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

