table MeasuresPrediction
	lineageTag: 0dae0237-d68c-4afd-a85f-a50d016b49e5

	measure 'Latest Action' =
			
			CALCULATE(
			    SELECTEDVALUE('PredictionData'[Calibrated_Action]),
			    FILTER(
			        ALL('PredictionData'),
			        'PredictionData'[Date] = [Latest Date Prediction]
			    )
			)
		lineageTag: e487299b-52a9-4d76-a7ae-437d8305a4b7

	measure 'Latest Alignment' =
			
			CALCULATE(
			    SELECTEDVALUE('PredictionData'[Alignment_Band]),
			    FILTER(
			        ALL('PredictionData'),
			        'PredictionData'[Date] = [Latest Date Prediction]
			    )
			)
		lineageTag: 0e9e367f-d70c-4322-b8b8-98acd2eac3ae

	measure 'Latest Guardrail' =
			
			CALCULATE(
			    MAX('PredictionData'[Guardrail]),
			    FILTER(
			        ALL('PredictionData'),
			        'PredictionData'[Date] = [Latest Date Prediction]
			    )
			)
		formatString: 0
		lineageTag: 382d29c5-514a-4504-8aea-7e98245327b7

	measure 'Latest Guardrail Label' =
			
			IF(
			    [Latest Guardrail] = 1,
			    "Unstable",
			    "Stable"
			)
		lineageTag: d466eed4-999f-4474-88a3-2d61d8881a55

	measure 'Latest Strength T21' =
			
			CALCULATE(
			    SELECTEDVALUE('PredictionData'[Strength_t21]),
			    FILTER(
			        ALL('PredictionData'),
			        'PredictionData'[Date] = [Latest Date Prediction]
			    )
			)
		lineageTag: 80995f6d-e70d-4ea2-8628-e6415250594b

	measure 'Latest Strength T28' =
			
			CALCULATE(
			    SELECTEDVALUE('PredictionData'[Strength_t28]),
			    FILTER(
			        ALL('PredictionData'),
			        'PredictionData'[Date] = [Latest Date Prediction]
			    )
			)
		lineageTag: d0634887-451e-4f93-b316-54a01c29da75

	measure 'Action Display' = ```
			
			VAR CurrentAction = [Latest Action]
			RETURN
			    SWITCH( TRUE(),
			        CONTAINSSTRING(CurrentAction, "Increase"), UNICHAR(9650) & " " & CurrentAction,
			        CONTAINSSTRING(CurrentAction, "Reduce"),   UNICHAR(9660) & " " & CurrentAction,
			        CONTAINSSTRING(CurrentAction, "Maintain"), UNICHAR(12288) & " " & CurrentAction,
			        CONTAINSSTRING(CurrentAction, "Monitor"),  UNICHAR(128065) & " " & CurrentAction,
			        CurrentAction -- Shows the original text if no keyword is found
			    )
			
			```
		lineageTag: 15642447-2c15-4292-a38e-0cc83f16392a

	measure 'Avg Occupancy' = AVERAGE('PredictionData'[Occupancy])
		lineageTag: de8ccd7c-bec9-4735-aa1c-29b00426c758

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Show Last 28 Days Aligned T21' =
			
			VAR LatestAlignedDate =
			    CALCULATE(
			        MAX('PredictionData'[Forecast_Date_t21]),
			        FILTER(
			            ALL('PredictionData'),
			            NOT ISBLANK('PredictionData'[target_t21])
			        )
			    )
			VAR CurrentAlignedDate =
			    MAX('PredictionData'[Forecast_Date_t21])
			RETURN
			    IF(
			        CurrentAlignedDate >= LatestAlignedDate - 27
			            && CurrentAlignedDate <= LatestAlignedDate,
			        1,
			        0
			    )
		formatString: 0
		lineageTag: 4941043d-2998-4da0-96d8-dd09015a2faa

	measure 'Avg Pred_t28' = AVERAGE('PredictionData'[Pred_t28])
		lineageTag: 079c9698-a86e-476d-b0d5-af132f217c1a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Pred_t21' = AVERAGE('PredictionData'[Pred_t21])
		lineageTag: d797148b-d1d8-4174-88cb-be48766d7b9c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg target_t21' = AVERAGE('PredictionData'[target_t21])
		lineageTag: f6294bfa-a2d9-48ca-aaf4-e40b605927db

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg target_t28' = AVERAGE('PredictionData'[target_t28])
		lineageTag: e12946f4-806a-4b5c-83f9-ec3729b995c0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Show Last 28 Days Aligned T28' =
			
			VAR LatestAlignedDate =
			    CALCULATE(
			        MAX('PredictionData'[Forecast_Date_t28]),
			        FILTER(
			            ALL('PredictionData'),
			            NOT ISBLANK('PredictionData'[target_t28])
			        )
			    )
			VAR CurrentAlignedDate =
			    MAX('PredictionData'[Forecast_Date_t28])
			RETURN
			    IF(
			        CurrentAlignedDate >= LatestAlignedDate - 27
			            && CurrentAlignedDate <= LatestAlignedDate,
			        1,
			        0
			    )
		formatString: 0
		lineageTag: bfde6e08-4fe8-4dbe-8c99-3d2e267d3fe1

	measure 'Show Next 28 Days Aligned T21' =
			
			VAR LatestActualDate =
			    CALCULATE(
			        MAX('PredictionData'[Date]),
			        ALL('PredictionData')
			    )
			VAR CurrentAlignedDate =
			    MAX('PredictionData'[Forecast_Date_t21])
			RETURN
			    IF(
			        CurrentAlignedDate > LatestActualDate
			            && CurrentAlignedDate <= LatestActualDate + 28,
			        1,
			        0
			    )
		formatString: 0
		lineageTag: dc70a379-b95a-42b9-8ef2-8a629fc36a38

	measure 'Show Next 28 Days Aligned T28' =
			
			VAR LatestActualDate =
			    CALCULATE(
			        MAX('PredictionData'[Date]),
			        ALL('PredictionData')
			    )
			VAR CurrentAlignedDate =
			    MAX('PredictionData'[Forecast_Date_t28])
			RETURN
			    IF(
			        CurrentAlignedDate > LatestActualDate
			            && CurrentAlignedDate <= LatestActualDate + 28,
			        1,
			        0
			    )
		formatString: 0
		lineageTag: 58a67a14-eddb-49a5-97e4-482f126246a9

	measure 'Show Last 28 Prediction Dates' =
			
			VAR LatestDate =
			    CALCULATE(
			        MAX('PredictionData'[Date]),
			        ALL('PredictionData')
			    )
			VAR CurrentDate =
			    MAX('PredictionData'[Date])
			RETURN
			    IF(
			        CurrentDate >= LatestDate - 27
			            && CurrentDate <= LatestDate,
			        1,
			        0
			    )
		formatString: 0
		lineageTag: 14eafc24-bd38-4481-abdd-6f8bd7d3f7e4

	measure 'Latest Date Prediction' =
			
			CALCULATE(
			    MAX(PredictionData[Date]),
			    ALL(PredictionData)
			)
		formatString: General Date
		lineageTag: 06c22257-d5c7-4cba-9073-f9002b3c355d

	column Column
		formatString: 0
		lineageTag: 02fb717a-7ac6-40c9-b9c4-26c0a763680c
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Column]

		annotation SummarizationSetBy = Automatic

	partition MeasuresPrediction = calculated
		mode: import
		source = Row("Column", BLANK())

	annotation PBI_Id = 014fe728a1ac434c9e68da8e233fb83c

	annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":""}

