table PredictionData
	lineageTag: 3bec6b50-3d11-4671-a8e5-390e45d86813

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2d9844a7-7373-468d-9990-931d7af4c4ff
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Occupied_Units
		dataType: int64
		formatString: 0
		lineageTag: 2ebdd29f-842d-4afc-ae57-24a5ae19ae69
		summarizeBy: sum
		sourceColumn: Occupied_Units

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: string
		lineageTag: e11adb58-c448-4005-b4e1-358502d34ba9
		summarizeBy: none
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column Occupancy
		dataType: double
		formatString: 0.000
		lineageTag: f62181cb-9fc2-4977-bc61-677695fb001a
		summarizeBy: sum
		sourceColumn: Occupancy

		annotation SummarizationSetBy = Automatic

	column Bookings
		dataType: int64
		formatString: 0
		lineageTag: ddb69af2-bfea-4906-8fd3-96f7fe3f0dac
		summarizeBy: sum
		sourceColumn: Bookings

		annotation SummarizationSetBy = Automatic

	column Notices
		dataType: int64
		formatString: 0
		lineageTag: 6c1a1f06-3088-455e-8d3c-032585a2aa83
		summarizeBy: sum
		sourceColumn: Notices

		annotation SummarizationSetBy = Automatic

	column Avg_Booking_Time
		dataType: double
		formatString: #,0.000
		lineageTag: d2fa1193-1e43-479f-8493-50971858704e
		summarizeBy: sum
		sourceColumn: Avg_Booking_Time

		annotation SummarizationSetBy = Automatic

	column Avg_Notice_Time
		dataType: double
		formatString: 0.000
		lineageTag: babb3027-a12b-4f1f-93a9-26009a82472d
		summarizeBy: sum
		sourceColumn: Avg_Notice_Time

		annotation SummarizationSetBy = Automatic

	column Has_Bookings
		dataType: int64
		formatString: 0
		lineageTag: 21037f63-fcea-4608-85ad-d8844f3d8a6a
		summarizeBy: sum
		sourceColumn: Has_Bookings

		annotation SummarizationSetBy = Automatic

	column Has_Notices
		dataType: int64
		formatString: 0
		lineageTag: 81ff70f7-3715-4048-bed4-be510c0c8e17
		summarizeBy: sum
		sourceColumn: Has_Notices

		annotation SummarizationSetBy = Automatic

	column units_available
		dataType: int64
		formatString: 0
		lineageTag: 5d86d646-dedf-4751-b2e8-e12012d9035d
		summarizeBy: sum
		sourceColumn: units_available

		annotation SummarizationSetBy = Automatic

	column Missing_Occupancy_Flag
		dataType: int64
		formatString: 0
		lineageTag: e311cca4-41c0-4c29-8127-e1c85499f0bc
		summarizeBy: sum
		sourceColumn: Missing_Occupancy_Flag

		annotation SummarizationSetBy = Automatic

	column Net_Flow
		dataType: int64
		formatString: 0
		lineageTag: c81d8ad1-946a-4c3c-86c4-e62cdac2bd98
		summarizeBy: sum
		sourceColumn: Net_Flow

		annotation SummarizationSetBy = Automatic

	column Demand_Pressure
		dataType: double
		formatString: 0.000
		lineageTag: ae3faf42-821a-4e17-8a39-b66fd3a05af5
		summarizeBy: sum
		sourceColumn: Demand_Pressure

		annotation SummarizationSetBy = Automatic

	column Booking_Intensity
		dataType: double
		formatString: 0.000
		lineageTag: 6589fdf0-a559-469d-b862-144c23e59b5b
		summarizeBy: sum
		sourceColumn: Booking_Intensity

		annotation SummarizationSetBy = Automatic

	column Notice_Pressure
		dataType: double
		formatString: 0.000
		lineageTag: 7872c7f1-1b6e-409c-b5c6-c1d50de5fe99
		summarizeBy: sum
		sourceColumn: Notice_Pressure

		annotation SummarizationSetBy = Automatic

	column Eff_Net_Flow
		dataType: double
		formatString: 0.000
		lineageTag: 8818c443-c54c-4e40-9887-093f04a6f940
		summarizeBy: sum
		sourceColumn: Eff_Net_Flow

		annotation SummarizationSetBy = Automatic

	column Eff_Net_Flow_Lag_1
		dataType: double
		formatString: 0.000
		lineageTag: 4209c63c-af96-4363-80cc-eb3a9a42cab8
		summarizeBy: sum
		sourceColumn: Eff_Net_Flow_Lag_1

		annotation SummarizationSetBy = Automatic

	column Eff_Net_Flow_Lag_7
		dataType: double
		formatString: 0.000
		lineageTag: 4879db1c-8cdf-4f51-bddc-c652d5d48f77
		summarizeBy: sum
		sourceColumn: Eff_Net_Flow_Lag_7

		annotation SummarizationSetBy = Automatic

	column Lag_1d
		dataType: double
		formatString: 0.000
		lineageTag: cc89fd71-3f4d-4d54-9df2-98cd08c3a78b
		summarizeBy: sum
		sourceColumn: Lag_1d

		annotation SummarizationSetBy = Automatic

	column Lag_2d
		dataType: double
		formatString: 0.000
		lineageTag: 56714e63-b75e-4f84-8743-9e6048bc62cc
		summarizeBy: sum
		sourceColumn: Lag_2d

		annotation SummarizationSetBy = Automatic

	column Lag_3d
		dataType: double
		formatString: 0.000
		lineageTag: 43285d6e-4dc3-4e3c-9832-13727efd130b
		summarizeBy: sum
		sourceColumn: Lag_3d

		annotation SummarizationSetBy = Automatic

	column Lag_7d
		dataType: double
		formatString: 0.000
		lineageTag: 086aa6b0-9b93-4868-86e0-c42fd2c8293c
		summarizeBy: sum
		sourceColumn: Lag_7d

		annotation SummarizationSetBy = Automatic

	column Lag_14d
		dataType: double
		formatString: 0.000
		lineageTag: c3108e04-21c0-436f-8070-9ea8809d39df
		summarizeBy: sum
		sourceColumn: Lag_14d

		annotation SummarizationSetBy = Automatic

	column Lag_21d
		dataType: double
		formatString: 0.000
		lineageTag: af5d7c41-4e50-4fde-8073-f19695b3f65d
		summarizeBy: sum
		sourceColumn: Lag_21d

		annotation SummarizationSetBy = Automatic

	column Lag_28d
		dataType: double
		formatString: 0.000
		lineageTag: 3b7a8bb7-5150-4518-86ab-74122c3a67f1
		summarizeBy: sum
		sourceColumn: Lag_28d

		annotation SummarizationSetBy = Automatic

	column Delta_1d
		dataType: double
		formatString: 0.000
		lineageTag: eb46f524-706c-4f93-a865-cec3d75d9f42
		summarizeBy: sum
		sourceColumn: Delta_1d

		annotation SummarizationSetBy = Automatic

	column Delta_2d
		dataType: double
		formatString: 0.000
		lineageTag: aa201f85-9848-4c83-9dcf-524b857cd9c6
		summarizeBy: sum
		sourceColumn: Delta_2d

		annotation SummarizationSetBy = Automatic

	column Acceleration
		dataType: double
		formatString: 0.000
		lineageTag: e2807305-aaeb-4aaf-a517-da7582651a4e
		summarizeBy: sum
		sourceColumn: Acceleration

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		formatString: 0
		lineageTag: 2665d3b3-f724-436f-a6d9-0edc581be4ea
		summarizeBy: sum
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayOfYear
		dataType: int64
		formatString: 0
		lineageTag: 36a973c3-0abb-4991-82ee-bed81437f213
		summarizeBy: sum
		sourceColumn: DayOfYear

		annotation SummarizationSetBy = Automatic

	column dow_sin
		dataType: double
		formatString: 0.000
		lineageTag: fe80e92f-234f-45f5-bb4f-4a921de5054a
		summarizeBy: sum
		sourceColumn: dow_sin

		annotation SummarizationSetBy = Automatic

	column dow_cos
		dataType: double
		formatString: 0.000
		lineageTag: d2f9cf02-19cb-4e4a-8c25-eafa3985f28f
		summarizeBy: sum
		sourceColumn: dow_cos

		annotation SummarizationSetBy = Automatic

	column doy_sin
		dataType: double
		formatString: 0.000
		lineageTag: 1b0d5eea-05d3-4166-b379-10b41201d719
		summarizeBy: sum
		sourceColumn: doy_sin

		annotation SummarizationSetBy = Automatic

	column doy_cos
		dataType: double
		formatString: 0.000
		lineageTag: 80848b08-b744-4e69-96d3-d8db59b85d60
		summarizeBy: sum
		sourceColumn: doy_cos

		annotation SummarizationSetBy = Automatic

	column Is_Christmas_Period
		dataType: int64
		formatString: 0
		lineageTag: 2eb39f02-7e1b-45fd-af60-a9e0fa342c2f
		summarizeBy: sum
		sourceColumn: Is_Christmas_Period

		annotation SummarizationSetBy = Automatic

	column Is_Summer_Period
		dataType: int64
		formatString: 0
		lineageTag: c153499e-ff14-4241-ade4-8e1020ebdc00
		summarizeBy: sum
		sourceColumn: Is_Summer_Period

		annotation SummarizationSetBy = Automatic

	column target_t1
		dataType: double
		formatString: 0.000
		lineageTag: 78af4270-960f-4896-8178-0b9e25388ceb
		summarizeBy: sum
		sourceColumn: target_t1

		annotation SummarizationSetBy = Automatic

	column target_t7
		dataType: double
		formatString: 0.000
		lineageTag: 93f724b5-ba99-4e83-a760-2d1bd5864a0d
		summarizeBy: sum
		sourceColumn: target_t7

		annotation SummarizationSetBy = Automatic

	column target_t14
		dataType: double
		formatString: 0.000
		lineageTag: 661628c3-7705-4b79-8494-b1d212a18958
		summarizeBy: sum
		sourceColumn: target_t14

		annotation SummarizationSetBy = Automatic

	column target_t21
		dataType: double
		formatString: 0.000
		lineageTag: c3aaf7a6-05e1-47a8-baac-16a478128b20
		summarizeBy: sum
		sourceColumn: target_t21

		annotation SummarizationSetBy = Automatic

	column target_t28
		dataType: double
		formatString: 0.000
		lineageTag: 2f055dc4-986b-447a-a442-5a93b213f57c
		summarizeBy: sum
		sourceColumn: target_t28

		annotation SummarizationSetBy = Automatic

	column delta_t1
		dataType: double
		formatString: 0.000
		lineageTag: 3962169e-dc58-4a55-a7f0-2fc816cf7da5
		summarizeBy: sum
		sourceColumn: delta_t1

		annotation SummarizationSetBy = Automatic

	column delta_t7
		dataType: double
		formatString: 0.000
		lineageTag: b9d6c913-6e35-4d8c-8b41-36ac60be453d
		summarizeBy: sum
		sourceColumn: delta_t7

		annotation SummarizationSetBy = Automatic

	column delta_t14
		dataType: double
		formatString: 0.000
		lineageTag: 78cfd8d6-2747-45cc-90ca-36a59f9e3bd1
		summarizeBy: sum
		sourceColumn: delta_t14

		annotation SummarizationSetBy = Automatic

	column delta_t21
		dataType: double
		formatString: 0.000
		lineageTag: d9fea4a9-640f-4140-9423-36d68a425b63
		summarizeBy: sum
		sourceColumn: delta_t21

		annotation SummarizationSetBy = Automatic

	column delta_t28
		dataType: double
		formatString: 0.000
		lineageTag: 5b76ecf9-3718-4a4f-b5fe-a1d524c3c81e
		summarizeBy: sum
		sourceColumn: delta_t28

		annotation SummarizationSetBy = Automatic

	column Seasonal_Avg
		dataType: double
		formatString: 0.000
		lineageTag: 8a00a379-7e6a-49c6-91c7-bdbead011dc4
		summarizeBy: sum
		sourceColumn: Seasonal_Avg

		annotation SummarizationSetBy = Automatic

	column Occ_vs_Seasonal
		dataType: double
		formatString: 0.0000000
		lineageTag: 7775ca74-f531-49b9-b273-434cf535efea
		summarizeBy: sum
		sourceColumn: Occ_vs_Seasonal

		annotation SummarizationSetBy = Automatic

	column Direction_t1
		dataType: int64
		formatString: 0
		lineageTag: f90f0a7b-e04c-48e8-9880-a30e31c8f99b
		summarizeBy: sum
		sourceColumn: Direction_t1

		annotation SummarizationSetBy = Automatic

	column Direction_t7
		dataType: int64
		formatString: 0
		lineageTag: 8ef2c654-ac57-4d9f-b99a-3d6363a721f1
		summarizeBy: sum
		sourceColumn: Direction_t7

		annotation SummarizationSetBy = Automatic

	column Pred_t7
		dataType: double
		formatString: 0.0000000
		lineageTag: 604c0265-bac7-49fe-9045-de99d650369c
		summarizeBy: sum
		sourceColumn: Pred_t7

		annotation SummarizationSetBy = Automatic

	column Pred_t14
		dataType: double
		lineageTag: a4705a77-2739-4306-91b1-b0aa12e1a4f7
		summarizeBy: sum
		sourceColumn: Pred_t14

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Pred_t21
		dataType: double
		lineageTag: 25c7389f-56a1-4210-9350-97bb088e9073
		summarizeBy: sum
		sourceColumn: Pred_t21

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Pred_t28
		dataType: double
		lineageTag: 4c8057cc-3abf-40e6-802c-486d97a792c1
		summarizeBy: sum
		sourceColumn: Pred_t28

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Pred_t1
		dataType: double
		lineageTag: 869cbe2b-2961-4fd0-9726-dee41c989b48
		summarizeBy: sum
		sourceColumn: Pred_t1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Prob_Down_t1
		dataType: double
		lineageTag: aa87c977-c9b0-49a1-acb6-3797991d011b
		summarizeBy: sum
		sourceColumn: Prob_Down_t1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Prob_Up_t1
		dataType: double
		lineageTag: e918f844-68a9-466e-9538-e50d0818920a
		summarizeBy: sum
		sourceColumn: Prob_Up_t1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Direction_Pred_t1
		dataType: int64
		formatString: 0
		lineageTag: 66c586d3-8337-40da-aa77-2d9e7dc7b1b2
		summarizeBy: sum
		sourceColumn: Direction_Pred_t1

		annotation SummarizationSetBy = Automatic

	column Prob_Down_t7
		dataType: double
		lineageTag: 6f77b224-2ab0-408c-9fc9-817e99454a3b
		summarizeBy: sum
		sourceColumn: Prob_Down_t7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Prob_Up_t7
		dataType: double
		lineageTag: 09824299-1016-4e81-81c7-2fcef27cdef9
		summarizeBy: sum
		sourceColumn: Prob_Up_t7

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Direction_Pred_t7
		dataType: int64
		formatString: 0
		lineageTag: 7c2c32e5-05b3-44c5-9949-76cdadbae1a3
		summarizeBy: sum
		sourceColumn: Direction_Pred_t7

		annotation SummarizationSetBy = Automatic

	column Prob_Down_t14
		dataType: double
		lineageTag: e0118543-daae-4dcc-ac06-2d2fc750db02
		summarizeBy: sum
		sourceColumn: Prob_Down_t14

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Prob_Up_t14
		dataType: double
		lineageTag: 9d56b409-2357-4f88-a862-5cdd6f18e3e5
		summarizeBy: sum
		sourceColumn: Prob_Up_t14

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Direction_Pred_t14
		dataType: int64
		formatString: 0
		lineageTag: 6dd5abfb-c0f4-4b88-a3bf-8b468f583af8
		summarizeBy: sum
		sourceColumn: Direction_Pred_t14

		annotation SummarizationSetBy = Automatic

	column Prob_Down_t21
		dataType: double
		lineageTag: 7e0c89ca-fdc7-4404-a233-d5cc28f64988
		summarizeBy: sum
		sourceColumn: Prob_Down_t21

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Prob_Up_t21
		dataType: double
		lineageTag: 6a13ab49-5839-41bb-9eba-a0f61a9e20d7
		summarizeBy: sum
		sourceColumn: Prob_Up_t21

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Direction_Pred_t21
		dataType: int64
		formatString: 0
		lineageTag: 21212fd7-5e8e-492a-8faa-dad6cf02eb85
		summarizeBy: sum
		sourceColumn: Direction_Pred_t21

		annotation SummarizationSetBy = Automatic

	column Prob_Down_t28
		dataType: double
		lineageTag: feeb1912-6303-4abc-b741-c8ee01c0a05e
		summarizeBy: sum
		sourceColumn: Prob_Down_t28

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Prob_Up_t28
		dataType: double
		lineageTag: 967a58d1-9579-49ec-8133-2393d6f1c86b
		summarizeBy: sum
		sourceColumn: Prob_Up_t28

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Direction_Pred_t28
		dataType: int64
		formatString: 0
		lineageTag: 963a1e73-a192-4971-a886-72b4addf97ef
		summarizeBy: sum
		sourceColumn: Direction_Pred_t28

		annotation SummarizationSetBy = Automatic

	column Strength_t7
		dataType: string
		lineageTag: 25ea5675-831b-4c8b-bb5a-5236fd704a00
		summarizeBy: none
		sourceColumn: Strength_t7

		annotation SummarizationSetBy = Automatic

	column Strength_t14
		dataType: string
		lineageTag: 8cb7e45f-5772-4a83-9bca-511a0a7a65f7
		summarizeBy: none
		sourceColumn: Strength_t14

		annotation SummarizationSetBy = Automatic

	column Strength_t21
		dataType: string
		lineageTag: 43027364-b94d-4757-a0ae-b12d5eeb77d5
		summarizeBy: none
		sourceColumn: Strength_t21

		annotation SummarizationSetBy = Automatic

	column Strength_t28
		dataType: string
		lineageTag: 54bbfdf5-b1b1-41bb-8f05-ffe4aee3af2b
		summarizeBy: none
		sourceColumn: Strength_t28

		annotation SummarizationSetBy = Automatic

	column Correct_t1_confident_only
		dataType: int64
		formatString: 0
		lineageTag: aff6ded0-6cc5-4aa1-a8aa-4e0ed99a0b8a
		summarizeBy: sum
		sourceColumn: Correct_t1_confident_only

		annotation SummarizationSetBy = Automatic

	column Matured_T1_Correct
		dataType: int64
		formatString: 0
		lineageTag: 016a3226-19ab-4b8f-a21c-456de68b4bfb
		summarizeBy: sum
		sourceColumn: Matured_T1_Correct

		annotation SummarizationSetBy = Automatic

	column Correct_t7_confident_only
		dataType: int64
		formatString: 0
		lineageTag: 5d09c757-20ce-4a9c-9aac-5d5c01f8de5c
		summarizeBy: sum
		sourceColumn: Correct_t7_confident_only

		annotation SummarizationSetBy = Automatic

	column Matured_T7_Correct
		dataType: int64
		formatString: 0
		lineageTag: ead7f2c6-d8f3-4d32-93d4-fdb6d4382f0c
		summarizeBy: sum
		sourceColumn: Matured_T7_Correct

		annotation SummarizationSetBy = Automatic

	column Recent_T1_Accuracy_21
		dataType: double
		lineageTag: 0a8b82b5-e161-4f39-9bda-9d501f7fe58d
		summarizeBy: sum
		sourceColumn: Recent_T1_Accuracy_21

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Recent_T7_Accuracy_21
		dataType: double
		lineageTag: 9aaa0349-957d-4f94-bf54-cf9e53236351
		summarizeBy: sum
		sourceColumn: Recent_T7_Accuracy_21

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Alignment_Score_21
		dataType: double
		lineageTag: 7b9b3145-9713-4530-ab06-6bd190f23c6c
		summarizeBy: sum
		sourceColumn: Alignment_Score_21

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Alignment_Band
		dataType: string
		lineageTag: 3f1426f2-1369-41d8-a057-a8123237be0e
		summarizeBy: none
		sourceColumn: Alignment_Band

		annotation SummarizationSetBy = Automatic

	column Guardrail
		dataType: int64
		formatString: 0
		lineageTag: 8bc0cab4-a4dd-4378-bfbf-49d42c4d18cc
		summarizeBy: sum
		sourceColumn: Guardrail

		annotation SummarizationSetBy = Automatic

	column Calibrated_Action
		dataType: string
		lineageTag: e525bebe-e1b9-4e59-9429-78da597cb4c2
		summarizeBy: none
		sourceColumn: Calibrated_Action

		annotation SummarizationSetBy = Automatic

	column Forecast_Date_t21 = 'PredictionData'[Date] + 21
		formatString: Short Date
		lineageTag: 68c7704b-6172-4c6f-a828-ade5c1de1d8d
		summarizeBy: none

		variation Variation
			isDefault
			relationship: b712b7cf-586b-4cb9-9cc1-556bfaf606ef
			defaultHierarchy: LocalDateTable_585cd57a-0930-44c7-99ab-42a60e0e9c61.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Forecast_Date_t28 = 'PredictionData'[Date] + 28
		formatString: Short Date
		lineageTag: 0bcf57ba-c6eb-4d7c-83fa-68c99d9d8331
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 914e318f-61dd-4e95-86a0-a55fc96e0d33
			defaultHierarchy: LocalDateTable_b13e6a6a-33f1-47a2-95c2-3726e1acbdcd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Strength Score T21' =
			
			SWITCH(
			    'PredictionData'[Strength_t21],
			    "STRONG_DOWN", -2,
			    "MODERATE_DOWN", -1,
			    "UNCERTAIN", 0,
			    "MODERATE_UP", 1,
			    "STRONG_UP", 2,
			    BLANK()
			)
		formatString: 0
		lineageTag: d8be23cd-c7f8-4603-a312-218baa183811
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Strength Score T28' =
			
			SWITCH(
			    'PredictionData'[Strength_t28],
			    "STRONG_DOWN", -2,
			    "MODERATE_DOWN", -1,
			    "UNCERTAIN", 0,
			    "MODERATE_UP", 1,
			    "STRONG_UP", 2,
			    BLANK()
			)
		formatString: 0
		lineageTag: 968a65e0-2d7e-4aba-935a-74f24e5f6a36
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition PredictionData = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\FiercePC\Desktop\CH_Data\ML\scored_operational_output.csv"),[Delimiter=",", Columns=85, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Occupied_Units", Int64.Type}, {"Week", type text}, {"Occupancy", type number}, {"Bookings", Int64.Type}, {"Notices", Int64.Type}, {"Avg_Booking_Time", type number}, {"Avg_Notice_Time", type number}, {"Has_Bookings", Int64.Type}, {"Has_Notices", Int64.Type}, {"units_available", Int64.Type}, {"Missing_Occupancy_Flag", Int64.Type}, {"Net_Flow", Int64.Type}, {"Demand_Pressure", type number}, {"Booking_Intensity", type number}, {"Notice_Pressure", type number}, {"Eff_Net_Flow", type number}, {"Eff_Net_Flow_Lag_1", type number}, {"Eff_Net_Flow_Lag_7", type number}, {"Lag_1d", type number}, {"Lag_2d", type number}, {"Lag_3d", type number}, {"Lag_7d", type number}, {"Lag_14d", type number}, {"Lag_21d", type number}, {"Lag_28d", type number}, {"Delta_1d", type number}, {"Delta_2d", type number}, {"Acceleration", type number}, {"DayOfWeek", Int64.Type}, {"DayOfYear", Int64.Type}, {"dow_sin", type number}, {"dow_cos", type number}, {"doy_sin", type number}, {"doy_cos", type number}, {"Is_Christmas_Period", Int64.Type}, {"Is_Summer_Period", Int64.Type}, {"target_t1", type number}, {"target_t7", type number}, {"target_t14", type number}, {"target_t21", type number}, {"target_t28", type number}, {"delta_t1", type number}, {"delta_t7", type number}, {"delta_t14", type number}, {"delta_t21", type number}, {"delta_t28", type number}, {"Seasonal_Avg", type number}, {"Occ_vs_Seasonal", type number}, {"Direction_t1", Int64.Type}, {"Direction_t7", Int64.Type}, {"Pred_t7", type number}, {"Pred_t14", type number}, {"Pred_t21", type number}, {"Pred_t28", type number}, {"Pred_t1", type number}, {"Prob_Down_t1", type number}, {"Prob_Up_t1", type number}, {"Direction_Pred_t1", Int64.Type}, {"Prob_Down_t7", type number}, {"Prob_Up_t7", type number}, {"Direction_Pred_t7", Int64.Type}, {"Prob_Down_t14", type number}, {"Prob_Up_t14", type number}, {"Direction_Pred_t14", Int64.Type}, {"Prob_Down_t21", type number}, {"Prob_Up_t21", type number}, {"Direction_Pred_t21", Int64.Type}, {"Prob_Down_t28", type number}, {"Prob_Up_t28", type number}, {"Direction_Pred_t28", Int64.Type}, {"Strength_t7", type text}, {"Strength_t14", type text}, {"Strength_t21", type text}, {"Strength_t28", type text}, {"Correct_t1_confident_only", Int64.Type}, {"Matured_T1_Correct", Int64.Type}, {"Correct_t7_confident_only", Int64.Type}, {"Matured_T7_Correct", Int64.Type}, {"Recent_T1_Accuracy_21", type number}, {"Recent_T7_Accuracy_21", type number}, {"Alignment_Score_21", type number}, {"Alignment_Band", type text}, {"Guardrail", Int64.Type}, {"Calibrated_Action", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

